#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by git-commit with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git-rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ascii filenames set this variable to true.
allownonascii=$(git config hooks.allownonascii)

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test "$(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0')"
then
	echo "Error: Attempt to add a non-ascii file name."
	echo
	echo "This can cause problems if you want to work"
	echo "with people on other platforms."
	echo
	echo "To be portable it is advisable to rename the file ..."
	echo
	echo "If you know what you are doing you can disable this"
	echo "check using:"
	echo
	echo "  git config hooks.allownonascii true"
	echo
	exit 1
fi

function get_backtrace
{
	failed_file="${pwd_str}/failed_test_cmd"
	if [ ! -f "$failed_file" ]; then
		# no fail file
		return
	fi
	failed_cmd=`cat ${pwd_str}/failed_test_cmd`
	failed_exec=`cut -f1 -d' ' "$failed_file"`
	failed_args=`cut -f2-8 -d' ' "$failed_file"`
	echo "---------------"
	echo "Failed command: ${failed_cmd}"
	echo "Re-executing to get backtrace."
	echo "---------------"
	cd src/
	echo "run $failed_args" >gdb_cmd
	echo "bt" >>gdb_cmd
	gdb $failed_exec -batch -x gdb_cmd
	cd ..
}

pwd_str=`pwd`
make tools
err=$?
if [ $err -ne 0 ]; then
	echo "Failed to build."
	exit $err
fi

echo "Testing POSIX interface"
pushd ${pwd_str}
make tests
popd

echo "Testing MMAP interface"
pushd ${pwd_str}
make tests-mmap
popd

err=$?
if [ $err -ne 0 ]; then
	echo "Tests failed."
	echo  "Fix it, Anthony"
	get_backtrace
	exit $err
fi

exec git diff-index --check --cached $against --
