.PHONY: tests
tests: tests-std

draw-relocs: tests
	util/draw_all_relocs.sh

DRAW_FS_HITS=$(FSNAMES:%=draw-hits-%)
draw-hits: $(DRAW_FS_HITS)
draw-hits-%: tests
	FSNAME=`echo $@ | cut -f3 -d-` util/draw_all_hits.sh

DRAW_FS_SCANS=$(FSNAMES:%=draw-scans-%)
draw-scans: $(DRAW_FS_SCANS)
draw-scans-%: tests
	util/draw.`echo $@ | cut -f3 -d-`.sh

paper: paper-gen paper-tests paper-draw
paper-gen: tests
paper-tests: tests-extra tests-extra-oprof tests-extra-stack tests-depth-stack tests-misc
paper-plot:
	./util/plot.sh
paper-draw: draw paper-plot


TEST_STD=$(FSNAMES:%=tests-std-%)
tests-std: $(TEST_STD)
tests-std-%: code tools
	TEST_FS=`echo $@ | cut -f3 -d-` tests/do_all_tests.sh

#TESTS_KERN=$(FSNAMES:%=tests-kern-%)
TESTS_KERN=	tests-kern-ext2		\
		tests-kern-vfat 	\
		tests-kern-iso9660	\
		tests-kern-reiserfs

# KVM shutdown after run
# should be ssh script??
tests-kern: $(TESTS_KERN)
	./util/qemu_shutdown.sh

tests-kern-%: kvm-started
	FSNAME=`echo $@ | cut -f3 -d'-'` tests/do_tests_kernel.sh

kvm-kill:
	killall -w qemu-system-x86_64

kvm-started: kern
	./util/run_qemu.sh &

DIRS_TEST=$(FSNAMES:%=dirs-test-%)
dirs-test: $(DIRS_TEST)
dirs-test-%:
	mkdir -p tests/scantool-`echo $@ | cut -f3 -d-`
	mkdir -p tests/relocate-`echo $@ | cut -f3 -d-`
	mkdir -p tests/defragtool-`echo $@ | cut -f3 -d-`
	mkdir -p tests/thrashcopy-`echo $@ | cut -f3 -d-`
	mkdir -p tests/smushtool-`echo $@ | cut -f3 -d-`
	mkdir -p tests/scattertool-`echo $@ | cut -f3 -d-`
	mkdir -p tests/fusebrowse-`echo $@ | cut -f3 -d-`
	mkdir -p tests/kernel-`echo $@ | cut -f3 -d-`
	mkdir -p tests/klee-`echo $@ | cut -f3 -d-`
	mkdir -p tests/fsck-`echo $@| cut -f3 -d-`

TEST_MMAP=$(FSNAMES:%=tests-mmap-%)
tests-mmap: $(TEST_MMAP)
tests-mmap-flags=TOOL_RT=mmap
tests-mmap-%: code tools
	$(tests-mmap-flags) TEST_FS=`echo $@ | cut -f3 -d-` tests/do_all_tests.sh

tests-misc:
	tests/do_tests_misc.sh

tests-linux-4gb: tests-linux-4gb-vfat tests-linux-4gb-ext2 tests-linux-4gb-reiserfs
tests-linux-4gb-vfat:
	FILESYSTEM=vfat USE_STATS="YES" tests/linux-4gb.sh
tests-linux-4gb-ext2:
	FILESYSTEM=ext2 USE_STATS="YES" tests/linux-4gb.sh
tests-linux-4gb-reiserfs:
	FILESYSTEM=reiserfs USE_STATS="YES" tests/linux-4gb.sh

TEST_EXTRA_MMAP=$(FSNAMES:%=tests-extra-mmap-%)
tests-extra-mmap: $(TEST_EXTRA_MMAP)
tests-extra-mmap-flags=TOOL_RT=mmap TEST_CONFIG="EXTRA" USE_STATS="YES"
tests-extra-mmap-%:
	$(tests-extra-mmap-flags) TEST_FS=`echo $@ | cut -f4 -d-`  tests/do_all_tests.sh

TEST_EXTRA=$(FSNAMES:%=tests-extra-draw-%)
tests-extra-draw: $(TEST_EXTRA)
tests-extra-draw-flags=TEST_CONFIG="EXTRA" USE_STATS="YES"
tests-extra-draw-%:
	$(tests-extra-draw-flags) TEST_FS=`echo $@ | cut -f4 -d-` tests/do_all_tests.sh
	./util/draw.`echo $@ | cut -f4 -d-`.sh

TEST_EXTRA_STD=$(FSNAMES:%=tests-extra-std-%)
tests-extra: tests-extra-std
tests-extra-std: $(TEST_EXTRA_STD)
tests-extra-std-flags=TEST_CONFIG="EXTRA" USE_STATS="YES"
tests-extra-std-%:
	$(tests-extra-std-flags) TEST_FS=`echo $@ | cut -f4 -d-` tests/do_all_tests.sh

TEST_EXTRA_TEMP=$(FSNAMES:%=tests-extra-temporal-%)
tests-extra-temporal: $(TEST_EXTRA_TEMP)
tests-extra-temporal-flags=TEST_CONFIG="EXTRA" USE_TEMPORAL="YES"
tests-extra-temporal-%:
	$(tests-extra-temporal-flags) TEST_FS=`echo $@ | cut -f4 -d-` tests/do_all_tests.sh

TEST_EXTRA_DISKSTAT=$(FSNAMES:%=tests-extra-std-%)
tests-extra-diskstat: $(TEST_EXTRA_DISKSTAT)
tests-extra-diskstat-flags=TEST_CONFIG="EXTRA" USE_SYNC="YES" USE_STATS="YES"
tests-extra-diskstat-%:
	$(tests-extra-diskstat-flags) TEST_FS=`echo $@ | cut -f4 -d-` tests/do_all_tests.sh

tests-depth-stack:
	tests/tests_depth.sh

TESTS_EXTRA_STACK=$(FSNAMES:%=tests-extra-stack-%)
tests-extra-stack: $(TESTS_EXTRA_STACK)
tests-extra-stack-%:
	TEST_CONFIG="STACK" TEST_FS=`echo $@ | cut -f4 -d-` tests/do_all_tests.sh


TESTS_EXTRA_MEM=$(FSNAMES:%=tests-extra-mem-%)
tests-extra-mem-stack: $(TESTS_EXTRA_MEM)
tests-extra-mem-%:
	TEST_CONFIG="MEM" TEST_FS=`echo $@ | cut -f4 -d-` tests/do_all_tests.sh

TESTS_EXTRA_OPROF=$(FSNAMES:%=tests-extra-oprof-%)
tests-extra-oprof: $(TESTS_EXTRA_OPROF)
tests-extra-oprof-%:
	TEST_CONFIG="EXTRA" USE_OPROF="YES" TEST_FS=`echo $@ | cut -f4 -d-`  tests/do_all_tests.sh

tests-clean:
	rm -f tests/misc/*
	rm -f tests/fsck-*/*
	rm -f tests/scantool-*/*
	rm -f tests/relocate-*/*
	rm -f tests/defragtool-*/*
	rm -f tests/thrashcopy-*/*
	rm -f tests/smushtool-*/*
	rm -f tests/scattertool-*/*
	rm -f tests/fusebrowse-*/*
	rm -f tests/kernel-*/*

###
# EARLY KLEE STUFF
###
KLEEFLAGS=	-max-instruction-time=30.  --max-memory-inhibit=false   --use-random-path \
		-max-static-fork-pct=30 -max-static-solve-pct=30 --max-static-cpfork-pct=30 \
		--disable-inlining --use-interleaved-covnew-NURS  --use-batching-search \
		--batch-instructions 1000   -weight-type=covnew  --only-output-states-covering-new \
		-use-cache -use-cex-cache --optimize -libc=uclibc -posix-runtime -init-env
KLEEENV=-sym-args 2 2 64 -sym-files  1 4194304

TESTS_KLEE=$(FSNAMES:%=tests-klee-%)
tests-klee: $(TESTS_KLEE)
tests-klee-%:
	mkdir -p tests/klee-`echo $@ | cut -f3 -d- `
	cp $(BINDIR)/klee/scantool-`echo $@ | cut -f3 -d- `.bc \
		tests/klee-`echo $@ | cut -f3 -d- `/
	cd tests/klee-`echo $@ | cut -f3 -d-` && \
	echo `pwd` && \
	$(KLEEBINDIR)/klee $(KLEEFLAGS) ./scantool-`echo $@ | cut -f3 -d-`.bc \
		$(KLEEENV)
