#ifndef FSL_IOCTL_H
#define FSL_IOCTL_H

#define FSLIO			0xf5
#define FSL_IOCTL_BLKDEVGET	_IO(FSLIO, 1)
#define FSL_IOCTL_BLKDEVPUT	_IO(FSLIO, 2)
#define FSL_IOCTL_DOTOOL	_IO(FSLIO, 3)

#define FSL_DOTOOL_SCATTER	0x0
#define FSL_DOTOOL_DEFRAG	0x1
#define FSL_DOTOOL_SMUSH	0x2
#define FSL_DOTOOL_VFS		0x3
#define FSL_MAX_DOTOOL		0x3

#endif